name: Update Sitemap on HTML Change

on:
  push:
    branches:
      - main
    paths:
      - '**.html'

jobs:
  update-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate sitemap if changed
        run: python sitemap_generator.py

      - name: Check if sitemap.xml changed
        id: check_diff
        run: |
          if git diff --quiet sitemap.xml; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap on HTML change"
          git push
